import { marketingConfig } from "@/config/marketing"
import { MainNav } from "@/components/main-nav"

export const metadata = {
  title: 'Create App',
  description: 'Generated by create next app',
}

export default function WorkspaceLayout({
  children
}: {
  children: React.ReactNode
}) {
  
  
  return (
    <>
      <MainNav items={marketingConfig.mainNav} />
      {children}
    </>
  )
}